//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookbook.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationContact
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public int TypeInformationContact { get; set; }
        public int Employe_id { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
